apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: clase11
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: clase11
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: germanjosepazcordon/back-clase11
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: clase11
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000