apiVersion: v1
kind: Namespace
metadata:
  name: clase11
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: clase11
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: germanjosepazcordon/back-clase11
        imagePullPolicy: Always
        name: backend
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: clase11
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: backend